In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

db_q1 = pd.read_excel("..//resources//2025_Q1_crime.xlsx")
db_q2 = pd.read_excel("..//resources//2025_Q2_crime.xlsx")
db_q3 = pd.read_excel("..//resources//2025_Q3_crime.xlsx")
db_q4 = pd.read_excel("..//resources//2025_Q4_crime.xlsx")

Import stuff and database

In [13]:
crimes = db_q1.groupby('LSOA code')['Crime type'].count().reset_index()
crimes.columns = ['LSOA', 'Crimes commited']
crimes

           LSOA  Crimes commited
0     E01000001                9
1     E01000002               25
2     E01000003               15
3     E01000005               62
4     E01000006               18
...         ...              ...
5840  W01001873                1
5841  W01001904                1
5842  W01001959                1
5843  W01002019                1
5844  W01002026                2

[5845 rows x 2 columns]

In [14]:
crimes = crimes.sort_values(by='Crimes commited',ascending=False)
crimes

           LSOA  Crimes commited
5821  E01035716             3679
4499  E01004763             2925
4475  E01004734             2846
4477  E01004736             1432
2328  E01002444             1326
...         ...              ...
4517  E01006013                1
4518  E01006134                1
4519  E01006170                1
4520  E01006305                1
5829  E01035741                1

[5845 rows x 2 columns]

In [15]:
crimes = crimes.nlargest(10,'Crimes commited')
crimes

           LSOA  Crimes commited
5821  E01035716             3679
4499  E01004763             2925
4475  E01004734             2846
4477  E01004736             1432
2328  E01002444             1326
5597  E01034220             1103
4455  E01004714             1079
4476  E01004735              917
2821  E01002968              902
879   E01000919              867

In [16]:
crime_types = db_q1.groupby('Crime type').size().reset_index(name = "count")
crime_types = crime_types.sort_values(by='count',ascending=False)
crime_types

                      Crime type  count
13  Violence and sexual offences  61068
0          Anti-social behaviour  50259
11         Theft from the person  23850
6                    Other theft  23393
12                 Vehicle crime  21454
10                   Shoplifting  20554
3      Criminal damage and arson  12708
8                   Public order  12259
2                       Burglary  12154
4                          Drugs  11866
9                        Robbery   7487
5                    Other crime   3352
1                  Bicycle theft   2696
7          Possession of weapons   1083