In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

db = pd.read_excel("..//resources//2025_01_metropolitan_street.xlsx")

Import stuff and database

In [9]:
crimes = db.groupby('LSOA code')['Crime type'].count().reset_index()
crimes.columns = ['LSOA', 'Crimes commited']
crimes

           LSOA  Crimes commited
0     E01000001                3
1     E01000002                9
2     E01000003                3
3     E01000005               20
4     E01000006                6
...         ...              ...
5222  E01035720                6
5223  E01035721               65
5224  E01035722               20
5225  W01000194                1
5226  W01001056                1

[5227 rows x 2 columns]

In [10]:
crimes = crimes.sort_values(by='Crimes commited',ascending=False)
crimes

           LSOA  Crimes commited
5218  E01035716             1196
4483  E01004763             1045
4459  E01004734             1004
4461  E01004736              514
2319  E01002444              480
...         ...              ...
4745  E01032714                1
4741  E01032638                1
4740  E01032637                1
1846  E01001954                1
1898  E01002006                1

[5227 rows x 2 columns]

In [12]:
crimes = crimes.nlargest(10,'Crimes commited')
crimes

           LSOA  Crimes commited
5218  E01035716             1196
4483  E01004763             1045
4459  E01004734             1004
4461  E01004736              514
2319  E01002444              480
5036  E01034220              360
4439  E01004714              352
2810  E01002968              303
4460  E01004735              303
875   E01000919              288

In [8]:
crime_types = db.groupby('Crime type').size().reset_index(name = "count")
crime_types = crime_types.sort_values(by='count',ascending=False)
crime_types

                      Crime type  count
13  Violence and sexual offences  19678
0          Anti-social behaviour  16138
6                    Other theft   7953
11         Theft from the person   7581
12                 Vehicle crime   7278
10                   Shoplifting   6858
2                       Burglary   4445
3      Criminal damage and arson   4157
4                          Drugs   4116
8                   Public order   3978
9                        Robbery   2457
5                    Other crime   1150
1                  Bicycle theft    837
7          Possession of weapons    326